In [1]:
import numpy as np

In [2]:
list(range(0,11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
#haciendo lo de arriba en sintaxis de numpy

#np.arange(inicio, limite, steps)
np.arange(0,11)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
#definir arreglos de ceros
np.zeros(3)
#nos sirve para hacer esquemas previos de arreglos
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
np.ones((10,5))
#similar a zeros

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
#genera estructuras de rangos con la cantidad de elementos especificadas
#np.lispace(inicio, limite, cantidad de datos)
np.linspace(0,10,10)
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [7]:
#Matriz identidad con numpy
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
#genera un valor aleatorio entre 0 y 1
np.random.rand()

0.8914454585909065

In [9]:
#se genera un array de valores aleatorio de 0 a 1 en un vector de 4 dimensiones
np.random.rand(4)

array([0.45679266, 0.00445172, 0.27536118, 0.67138612])

In [10]:
np.random.rand(4,4)

array([[0.62507756, 0.60213834, 0.12098147, 0.25939214],
       [0.43511338, 0.26746326, 0.81242322, 0.52253162],
       [0.47271032, 0.82465639, 0.69838943, 0.05836022],
       [0.11617933, 0.34111458, 0.48470405, 0.19904631]])

In [11]:
np.random.randint(1,15)

2

In [12]:
#se generan valores random en estructuras matriciales
#np.random.randint(inicio, limite, (columnas * filas))
np.random.randint(1,100,(10,10))

array([[86, 46, 72, 50, 16,  4, 11,  7,  1, 58],
       [76,  7, 42, 85, 68, 20, 36, 44, 69, 63],
       [18, 32, 58, 13,  9, 79, 83, 93, 83, 43],
       [80, 77, 35, 94, 96, 55, 80, 10, 84, 11],
       [83, 39,  4, 12, 55, 38, 89, 31, 24, 15],
       [ 5,  2, 91, 63, 34, 14, 75, 29, 79, 81],
       [31, 29, 38, 97, 20, 67,  6, 48, 72, 86],
       [30, 85, 39, 37, 59, 89, 28, 87,  9, 79],
       [44, 44, 17, 45, 77, 29, 61,  9, 58, 47],
       [54, 85, 21, 79, 64, 67, 34, 50, 48,  6]])