In [1]:
#aqui importamos la libreria
import numpy as np

In [3]:
#definimos una lista tradicional
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
#asi la convertimos en un array
arr = np.array(lista)
type(arr)

numpy.ndarray

In [8]:
#objetos de multiples dimensiones matrices
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
#indexado con arreglos
arr
arr[1]
arr[0] + arr[5]

7

In [14]:
#los indices seleccionan las filas dentro de las matrices
matriz[0]
matriz[2]
#acceder a un punto especifico de la matriz
matriz[0,2]

3

In [18]:
arr
#usando slices para encontrar valores dentro de un array
arr[0:3:]
#lista invertida
arr[::-1]
#saltando dos en dos
arr[::2]

array([1, 3, 5, 7, 9])

In [20]:
#usando slices con una matriz
# matriz[nivel de filas, nivel de columnas]
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])