In [1]:
import numpy as np

In [10]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arrsample = arr[0:6:]
arrsample

array([0, 1, 2, 3, 4, 5])

In [12]:
arrsample[:] = 0
arrsample

array([0, 0, 0, 0, 0, 0])

In [13]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [15]:
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [16]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [17]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])