In [1]:
"""Vamos a definir una dimension en python"""
#importamos numpy
import numpy as np

**Tipos de dimensiones en los datos**


1.   Escalar = objeto sin dimensiones un elemento dentro de un vector
2.   Vector = objeto de una dimension una columna dentro de una matriz
3.   Matriz = es un objetoco con 2 dimensiones, se puede tener una matriz de 3 dimensiones
4.   Tensor = objeto de n dimensiones



In [2]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [3]:
vector = np.array([42,22,4,887,32,215,668])
print(vector)
vector.ndim

[ 42  22   4 887  32 215 668]


1

In [6]:
matriz = np.array([[42,22,4,887,32,215,668],[344,67,122,54678,121,5565,99],[34,7,12,546,11,55,99]])
print(matriz)
matriz.ndim

[[   42    22     4   887    32   215   668]
 [  344    67   122 54678   121  5565    99]
 [   34     7    12   546    11    55    99]]


2

In [8]:
tensor = np.array([[[42,22,4,887,32,215,668],[344,67,122,54678,121,5565,99],[34,7,12,546,11,55,99]],[[42,22,4,887,32,215,668],[344,67,122,54678,121,5565,99],[34,7,12,546,11,55,99]]])
print(tensor)
tensor.ndim

[[[   42    22     4   887    32   215   668]
  [  344    67   122 54678   121  5565    99]
  [   34     7    12   546    11    55    99]]

 [[   42    22     4   887    32   215   668]
  [  344    67   122 54678   121  5565    99]
  [   34     7    12   546    11    55    99]]]


3

## Agregar o eliminar dimensiones

In [12]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [14]:
#expandiendo dimensiones en filas
expands = np.expand_dims(np.array([1,2,3]), axis = 0)
print(expands)
expands.ndim

[[1 2 3]]


2

In [15]:
#squeeze comprime las dimensiones a la optima
print(vector, vector.ndim)
vector2 = np.squeeze(vector)
print(vector2, vector2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
