In [3]:
import numpy as np

In [17]:
#Genera un arreglo de valores enteros aleatorios
arr = np.random.randint(1,20,10)
arr

array([10,  5,  4, 19, 15, 11,  4,  9, 12,  4])

In [18]:
#Transformando la forma de ese arreglo a matriz de 2 filas y 5 columnas
matriz = arr.reshape(2,5)
matriz

array([[10,  5,  4, 19, 15],
       [11,  4,  9, 12,  4]])

In [19]:
#numero maximo de un arreglo
arr.max()

19

In [20]:
#numero maximo de una matriz
matriz.max()

19

In [21]:
#numero maximo de una matriz en la fila 1
matriz.max(1)

array([19, 12])

In [22]:
#Este comando te arroja la posicion en la que se encuentra el valor maximo dentro de un arreglo
arr.argmax()

3

In [23]:
#este comando te arroja las posiciones donde se encuentran el valor maximo dentro de la matriz a nivel de filas
matriz.argmax(0)

array([1, 0, 1, 0, 0])

In [24]:
#para encontrar el minimo
arr.min()

4

In [25]:
arr.argmin()

2

In [26]:
matriz.min()

4

In [27]:
matriz.argmin()

2

In [28]:
arr

array([10,  5,  4, 19, 15, 11,  4,  9, 12,  4])

In [29]:
#vamos a usar peak to peak distancia del menor al mayor
arr.ptp()

15

In [30]:
matriz.ptp(0)

array([ 1,  1,  5,  7, 11])

In [33]:
#percentiles
np.percentile(arr,50)

9.5

In [34]:
np.percentile(arr,10)

4.0

In [35]:
#se ordenan los datos de un arreglo
arr.sort()
arr

array([ 4,  4,  4,  5,  9, 10, 11, 12, 15, 19])

In [37]:
#mediana de un arreglo
np.median(arr)

9.5

In [38]:
#para las matrices la mediana
np.median(matriz, 0)

array([ 7. ,  7.5,  8. , 10. , 14. ])

In [39]:
#Desviacion standar
np.std(arr)

4.8999999999999995

In [40]:
#varianza
np.var(arr)

24.009999999999998

In [41]:
#media
np.mean(arr)

9.3

In [43]:
# 
a = np.array([[1,2],[3,4]])
a
b = np.array([5,6])
b

array([5, 6])

In [47]:
a.ndim
#2
b.ndim
#1
b = np.expand_dims(b,axis=0)

In [48]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
#np.concatenate((a,b),axis=1)
#un error
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])