In [1]:
#Vamos a conocer la forma que tiene un array
import numpy as np

In [6]:
arr = np.random.randint(1,10,(3,2))
arr

array([[6, 3],
       [4, 3],
       [2, 3]])

In [8]:
#usando shape conocemos cuantas filas y columnas tenemos en un objeto
arr.shape

(3, 2)

In [9]:
#Esto sirve para cambiar la forma del arreglo de un objeto o matriz
arr.reshape(1,6)

array([[6, 3, 4, 3, 2, 3]])

In [10]:
np.reshape(arr,(1,6))

array([[6, 3, 4, 3, 2, 3]])

In [11]:
arr

array([[6, 3],
       [4, 3],
       [2, 3]])

In [12]:
#Arreglos con forma en lenguaje C
np.reshape(arr,(2,3),'C')

array([[6, 3, 4],
       [3, 2, 3]])

In [13]:
#Arreglos con forma en Lenguaje Fortran
np.reshape(arr,(2,3),'F')

array([[6, 2, 3],
       [4, 3, 3]])

In [15]:
#Este caso genera una optimizacion del arreglo usando A
np.reshape(arr,(2,3),'A')

array([[6, 3, 4],
       [3, 2, 3]])